### ISSUE TITLE
Exporter fails to fetch some of the metrics

### ISSUE THREAD

**Issue by YordanPavlov** [31z4/ethereum-prometheus-exporter#14]
Using the latest docker image of the exporter (31z4/ethereum-prometheus-exporter:v1.1.0) and a recent Parity Node Image (v2.7.2-stable) the following errors are shown.
```
2020/07/06 14:07:24 error gathering metrics: 3 error(s) occurred:
* error collecting metric Desc{fqName: "eth_sync_starting", help: "the block at which the import started", constLabels: {}, variableLabels: []}: not syncing
* error collecting metric Desc{fqName: "eth_sync_current", help: "the number of most recent block", constLabels: {}, variableLabels: []}: not syncing
* error collecting metric Desc{fqName: "eth_sync_highest", help: "the estimated highest block", constLabels: {}, variableLabels: []}: not syncing
```

As result the corresponding metrics are not fetched. Do you know if those metrics are still available maybe through a new name?

**Comment by 31z4** [comment]
This is expected behaviour when a node is not syncing.

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
