### ISSUE TITLE
eth_block_timestamp error

### ISSUE THREAD

**Issue by deepakjuit** [31z4/ethereum-prometheus-exporter#29]
* error collecting metric Desc{fqName: "parity_net_active_peers", help: "number of active peers", constLabels: {}, variableLabels: []}: the method parity_netPeers does not exist/is not available
* error collecting metric Desc{fqName: "parity_net_connected_peers", help: "number of peers currently connected to this client", constLabels: {}, variableLabels: []}: the method parity_netPeers does not exist/is not available
* error collecting metric Desc{fqName: "eth_block_timestamp", help: "timestamp of the most recent block", constLabels: {}, variableLabels: []}: invalid argument 1: json: cannot unmarshal number into Go value of type bool
2022/08/29 12:57:47 error gathering metrics: 3 error(s) occurred:

**Comment by 31z4** [comment]
First two errors might mean that you either don't run an [OpenEthereum](https://openethereum.github.io) node or disabled `parity` HTTP JSON-RPC APIs on the node.

The last one looks like a legitimate error which I was able to reproduce. Working on a fix.
